### ISSUE TITLE
operating theatre

### ISSUE THREAD

**Issue by genghiskhanofnz** [IDEMSInternational/carbonr#16]
I am facing a challenge to calculate hospital operating theatre  carbon.  Main items  are energy (electricity and gas), clinical  waste, general waste and disposables.  Most can be measured = good news.  By having a function in carbonr, this package will surely contribute to the clinical community.  Clinical waste = syringes, needles, specimens (an old liver in liver transplant) = measured in kg.  Another item is anesthetic gas that comes in liquid  form in litre before vaporised = measurable too in kg.  Wondering if a function could be created.  Thanks heaps.

**Comment by genghiskhanofnz** [comment]
Cost input could be a possibility too, mentioned in Add "materials" and "waste" functions #13.  Our hospital clinical costing systems could provide overall itemised theatre costs.  Wondering what your thoughts are.  Thank you very much.

**Comment by lilyclements** [comment]
This is a really interesting concept, and one that I would be excited to have in the package. I am happy to work on it and add it in, or if you would rather work on it then it is an open-source project, so we can collaborate there.

All the carbon-equivalent estimates have come from Government Reports, do you have literature references that can be openly discussed on measuring these items, or on how these relate to the government reports? I can see the direct link for some items such as electricity/gas, but how about for clinical waste?

**Comment by genghiskhanofnz** [comment]
I am so glad that today I receive your reply.  I am hoping carbonr can implement it soon.  I can give you the t CO2-e conversion from clinical waste that is usually incenerated.  Clinical waste t CO2-e = Q x EF.  Q = tonnes of wet weight.  EF = emission factor = 0.879.  Page 32 of Australian greenhouse 2022 document https://www.dcceew.gov.au/climate-change/publications/national-greenhouse-accounts-factors-2022.  All other items are already in your package.  One thing, I am planning to write a paper on it by acknowledging your package and your contribution.  Wondering if you could help.  Thank you so much.

**Comment by genghiskhanofnz** [comment]
read, incinerated in the above comment.  typo.

**Comment by lilyclements** [comment]
Sounds like a really interesting project you're working on - what is the paper on and your area of research on? Just for context, and out of interest. Happy to arrange a meeting if that is an easier way to discuss.

I have had a little think and wanted to check by you how I see the function so far. Perhaps if we had a `clinical_waste` function that you can use directly, and this calls various bits from other created functions. 

In PR #21 is a draft for this `clinical_waste` function. This has taken all the electricity, gas, and water emissions related parameters from `building_emissions` (previously known as `office_emissions`), and added a new parameter `wet_clinical_waste`. Here, if you input your clinical waste in wet weight, then it outputs the estimated CO2e emissions using your formula.

We currently have the following parameters:
* `wet_clinical_waste` Amount of (wet) clinical waste that is usually incinerated.
* `wet_clinical_waste_unit` Unit for `wet_clinical_waste` variable. Options are `"tonnes"` or `"kg"`.
* `water_supply` Amount of water used in the operating theatre
* `water_trt` logical. Default \code{TRUE}. Whether to include emissions associated with water treatment for used water.
* `water_unit` Unit for `water_supply` variable. Options are `"cubic metres"` or `"million litres"`.
* `electricity_kWh` Electricity used in kWh.
* `electricity_TD` logical. Default \code{TRUE}. Whether to include emissions associated with grid losses.
* `electricity_WTT` logical. Default \code{TRUE}. Whether to include emissions associated with extracting, refining, and transporting fuels.
* `heat_kWh` heat and steam used in kWh.
* `heat_TD` logical. Default \code{TRUE}. Whether to include emissions associated with grid losses.
* `heat_WTT` logical. Default \code{TRUE}. Whether to include emissions associated with extracting, refining, and transporting fuels.

Which elements from materials and waste functions would you be interested in? We can offer any under "Material Use" and "Waste Disposal" from the **Conversion Factors: 2022: Full Set** data spreadsheet available for download [here](https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2022). I will create a material and waste disposal function, and we can call the relevant materials/wastes from there.

You've also mentioned you'd like "anesthetic gas" as an option. There have a list of gases/fuels that we have been able to add in from the UK Government report (under the "Fuels" tab). However, I'm not convinced any here would relate to anaesthetic gas. Do you have an idea in mind of how we can measure this?

A final point is that it would be great if, in the future, we incorporate in the Australian factors from the document you shared (e.g., all the scope 1 and 3 emissions). However, since I am a bit preoccupied with a few other projects I'll write an issue on that, and can get back to that at a later date.

**Comment by genghiskhanofnz** [comment]
First and foremost, thanks for getting back to me with details = Amazing indeed. 

It seems to be that you have nearly completed my request.  Thank you very much.

A few issues remain as follows:
 
1. Anesthetic gas = nitrous oxide and volatile fluorinated liquids (isoflurane, desflurane, sevoflurane) vaporised before administering = I do not have any conversion data to t CO2-e
2. heating and air conditioning = big part of theatre waste = I am sure you could provide since it will  be similar to office buildings
3. Material use tab from the UK 2022 spreadsheet = Plastic is rampant in the operating thestres.  Would love to include as a function or argument in a combined operating_theatre_waste function.  They are measured in kg when wheelies are put on the scale. 
4. Waste disporal tab = interested in all activities except construction.  Nice to have in the operating_theatre_waste function as an argument. 

Happy to discuss on Zoom or Teams meeting.  Please let me know your availability.

My project is _embargoed_ to protect novel ideas from being copied before published (my university requirement).

However, I am open and happy to invite you as my co-investigator and co-author since your package is so valuable and one of its kind! 

If you have a beta, then may I have a testing?

See you soon.

**Comment by lilyclements** [comment]
Great. I'll have a start on that and let you know how I get on. Would you like a beta of the function or a beta of the package? The function set up is currently in PR #21 which can be tested once merged. Happy to merge that if you want to have a look at it now.

A really useful insight would be to know how you use the function. For example, you say that you measure plastic weight in kgs already. Do you put that information in a data set at all? I only ask because if there were a data set then we can create a function that reads in the data set, runs the `clinical_waste` function, and automatically outputs the CO2e emissions to make it easier to use. Perhaps that's something to discuss on a call.

Completely understand the university requirement. It would be great to get involved in the project - let's arrange a Zoom meeting to discuss this and other bits about the package. I'll pop my email here for now so that we can arrange via email (but will edit and remove it from this post) - lily@idems.international

Looking forward

**Comment by genghiskhanofnz** [comment]
Have emailed you just now from my uni.
Shall we discuss on the call?
Thank you so much.
P.S; you can remove your email from here

**Comment by genghiskhanofnz** [comment]
@lilyclements Thanks for reopening.
May I request for a comprehensive 'theatre_waste' function taking df with different waste types and outputs of CO2-e and monetary values df with plot function embedded?  Thank you so much.

**Comment by lilyclements** [comment]
Thanks for this! I have started on this function and have a few points. 

There's a lot in the waste and materials sheets/functions. Can you have a look at the options given in the "clinical_theatre_emissions" function and let me know which, if any, can be removed (for example, there's ten types of plastic - average, average_film, average_rigid, HDPE, LDPE, LLDPE, PET, PP, PS, PVC).

What gas would generally be used? The `raw_fuels` sheet and function show all the different options here. Can you let me know which ones are most appropriate?

Do you have a reference for your carbon credit unit price?

I need to still find conversion data for:
* Anesthetic gas
* Air conditioning (might have to go to the Australian document for this - I didn't see it in the UK document, but I'll double check. AC is less common in the UK since we do not know what the sun is!).

**Comment by genghiskhanofnz** [comment]
@lilyclements 
Thanks for your efforts in this.
1. Please leave plastic functions with all options open for now.  I will confirm with our hospital's waste manager to see what types of plaastic common in theatres.  Most probably is PVC.
2. Anesthetic gas commonly used = N2O and Isofluorene.  I need to find out any conversion available.  For the time being, please assume that no anesthetic gas is wasted since I fail to find any academic paper mentioning any evidence about its waste.
3. My perception is that heating data are available from UK.
4. Hospitals use HVAC negative pressure cooling system to keep infection out.  This one shows methodology for hospital cooling in its Appendix.
https://www.k-cep.org/wp-content/uploads/2018/10/Kigali_CEP_GlobalHospitalCooling_102418.pdf

**Comment by lilyclements** [comment]
Great! Thanks. All sounds good - to follow up to number 1: How about the other options - different papers, metals, electric appliances? They should be visible in the help file in the function but I can list them here if easier. 

Thanks!

**Comment by genghiskhanofnz** [comment]
@lilyclements 
I found a HVAC Austrtalia document here on page-45 = annual 144.3 KWh/m2 where we can plug in m2 values from a specific hospital operating theatres floor area = then we can get t CO2-e result from it.
https://www.airahfiles.org.au/i-Hub/M7/Report_LLHC5_Net-Zero-Energy-Emissions.pdf

**Comment by genghiskhanofnz** [comment]
@lilyclements 
We could remove metals and elec appliances because not much relevant to operating theatres.
Papers are relevant.
I am currently looking at the help display in  R function.  Thanks for that.

**Comment by genghiskhanofnz** [comment]
Would be even better if the function could accept 'wide' df and emission + credit values as df for different theatres in one go.

@lilyclements the reference for credit is here for Australia.
https://www.cleanenergyregulator.gov.au/Infohub/Markets/Pages/qcmr/december-quarter-2022/Australian-carbon-credit-units-(ACCUs).aspx 
Quarterly Carbon Market Reports will tell us the $ in the above link.  
It is quarterly but seems to be OK for your function.
Full implementation of carbon credit exchange will happen in this year 2023 according to the report above.

Cheers.

**Comment by lilyclements** [comment]
@genghiskhanofnz thank you for all of this. It’s very useful and I’ll update you he function accordingly.

Wide data is absolutely fine - can you give an example of the wide data frame so that I can ensure I’m working with the correct variables etc to make longer.

**Comment by lilyclements** [comment]
> @lilyclements I found a HVAC Austrtalia document here on page-45 = annual 144.3 KWh/m2 where we can plug in m2 values from a specific hospital operating theatres floor area = then we can get t CO2-e result from it. https://www.airahfiles.org.au/i-Hub/M7/Report_LLHC5_Net-Zero-Energy-Emissions.pdf

@genghiskhanofnz this is useful but I need to just clarify a few bits:

The Australian HVAC document shows the annual estimate at 144.3 KWh/m2. Currently, we have had a time estimate of "per operation" or "per day" rather than a yearly estimate. Do you see the function as being used "per day", or more "per year". This doesn't matter with how the function has been set up, but I'm just wondering.
How we currently calculate CO2e for amenities such as electricity, plastic waste, etc, we assume that the user has calculated the kWh (or kgs, litres, or appropriate unit) and inputs that value.
Is the kWh for air conditioning a readily available value (like electricity, water, etc is). If not, it looks quite complicated to have a calculation for this. It depends on the size of the operating theatre and what not. We could have that calculation as a separate function but the user would need to read in: hospital name and floor size (m2). We would also need to think about how to convert the time to be "per time frame given" rather than per year.

In the methodology of the first document shared they state:

> The energy used [...] was converted into equivalent kWh, thereby representing all as indirect emissions (e.g., this
assumes that natural gas emissions are similar to the country’s current grid CO2e intensity)

So if we have a kWh value for the HVAC, am I correct in assuming we can then calculate CO2e by using the electricity conversion from kWh to CO2e that is currently in the calculation?

**Comment by lilyclements** [comment]
> @lilyclements We could remove metals and elec appliances because not much relevant to operating theatres. Papers are relevant. I am currently looking at the help display in R function. Thanks for that.

@genghiskhanofnz Great, thanks! I noticed a lot on freezers/fridges values when looking through the literature. Is this an electrical appliance we would want to include, or does this all come in with the HVAC?

**Comment by genghiskhanofnz** [comment]
@lilyclements for sample df in 'long' format listing only one waste type 'wet_clinical_waste' for 5 theatres in 3 months observations.  Real world settings will include all relevant waste types and measures per date of observations, monthly or quarterly or yearly.  

input.df <- tibble::tribble(
        ~date,   ~location,          ~waste_type, ~waste_measure,
  "1/06/2023", "theatre01", "wet_clinical_waste",          1000L,
  "1/06/2023", "theatre02", "wet_clinical_waste",          1100L,
  "1/06/2023", "theatre03", "wet_clinical_waste",          1200L,
  "1/06/2023", "theatre04", "wet_clinical_waste",          1300L,
  "1/06/2023", "theatre05", "wet_clinical_waste",          1400L,
  "1/07/2023", "theatre01", "wet_clinical_waste",          1250L,
  "1/07/2023", "theatre02", "wet_clinical_waste",          1350L,
  "1/07/2023", "theatre03", "wet_clinical_waste",          1400L,
  "1/07/2023", "theatre04", "wet_clinical_waste",          1350L,
  "1/07/2023", "theatre05", "wet_clinical_waste",          1200L,
  "1/08/2023", "theatre01", "wet_clinical_waste",          1620L,
  "1/08/2023", "theatre02", "wet_clinical_waste",          1710L,
  "1/08/2023", "theatre03", "wet_clinical_waste",          1420L,
  "1/08/2023", "theatre04", "wet_clinical_waste",          1200L,
  "1/08/2023", "theatre05", "wet_clinical_waste",          1350L
  )
Created on 2023-06-13 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by genghiskhanofnz** [comment]
@lilyclements Users can get HVAC KWh readily from building management systems of the hospital.  Therefore,  this issue is settled for now.

Theatres hold medical freezers and fridges.  
"There is a blood fridge in theatre and a pharmacy fridge plus ones for staff food etc. not one in each theatre though"
Quote from our anesthetist.
So, we should keep them in the function.  
It is different from HVAC, which is only for cooling.

I hope I answer all your questions of 1.  df;  2.  elec appliances;  3.  HVAV KWh;  4.  carbon price documentation

**Comment by genghiskhanofnz** [comment]
May I add this for anesthetics?

Novosel, S., Prangenberg, C., Wirtz, D. C., Burger, C., Welle, K., & Kabir, K. (2022). Climate change: how surgery contributes to global warming. Chirurgie, 93(6), 579-585. doi:10.1007/s00104-021-01551-1

Up to 20% of volatile nonmetabolized anesthetic agents are vented into the stratosphere and destroy the ozone layer. Intravenous anesthetic drugs should be used whenever possible instead.

We, at the moment, consider no waste from anesthesia.

Users can put the % of waste as input.  We still need a conversion factor to tCO2-e.
Cheers.

**Comment by lilyclements** [comment]
@genghiskhanofnz thanks for this - I have added the fridges/freezers information in. I will add in carbon price information shortly.

**Some notes:**
> Would be even better if the function could accept 'wide' df and emission + credit values as df for different theatres in one go.
Sorry for not being clear - you gave an example with a long df, can you give an example on a wide data frame so I can sort the function as appropriate. It should be working for a long df at the moment. 

**Remaining items:**
* Users can get HVAC KWh readily from building management systems of the hospital. Therefore, this issue is settled for now.
* Anesthetics estimate: conversion factor to tCO2-e.

**Comment by lilyclements** [comment]
For Anesthetics estimates - 

I found the following paper which looks very interesting and comprehensive in their "cradle-to-gate" Greenhouse Gas Emissions for 20 **injectable anesthesic drugs** - https://pubs.acs.org/doi/pdf/10.1021/acssuschemeng.8b05473

These twenty anesthetic drugs with their respective cradle-to-gate GHG emissions are given in table S.2 under "Supporting Information"

We can include this for **injectable** drugs.

From other lookings around, there are two inhalational anaesthetics that are coming up a lot - Sevoflurane and Desflurane. Using results from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9413181/#R5 we can see that the CO2e emissions in kilograms are **Kg x GWP**

sevoflurane: GWP = 130
desflurane: GWP = 2540

We can convert them in mL to Kg too by:
sevoflurane: 250mL is approximately 0.3769kg
desflurane: 250mL is 0.34882kg

I've seen that TIVA is substantially lower so we should include their CO2e emissions as well. From what I can see TIVA is from the intravenous route. However, can you enlighten me somewhat here as the expert on the medical side of it all! - is TIVA an injectable anaesthetic? If so, are the 20 given above examples of a TIVA anaesthetic?

Thanks very much!

**Comment by lilyclements** [comment]
Are the emissions emitted from the use of the injectable anaesthetic included in "Cradle-to-Gate"? (As in, is it the cradle-to-gate that counts for most of the emissions, or is it using it itself?).

**Comment by genghiskhanofnz** [comment]
@lilyclements agree with anaethtic_emissions function for 5 options and include TIVA + other injectables at your discretion.

Our hospital anaethetist says "Tiva is propofol yes.  ...uses mainly sevo and some des and no longer any iso. some use of N2O but difficult to quantify a number per case, although we can roughly estimate it. Des has dropped a lot over last decade but not entirely gone from practice"

I hope the above quote will help your decision.

**Comment by lilyclements** [comment]
@genghiskhanofnz - Excellent, thanks. Really useful to have input from your hospital anaethetist too

**Comment by lilyclements** [comment]
`anaesthetic_emissions` have now been added. Left to sort:

- [] Add in carbon price information shortly.
- [] HVAC is not a problem for now, but will be something to consider in the future. 

Just realised you already gave an example of a wide data frame format - my apologies. It currently works for a wide data frame format. I can write a (wrapper) function to translate a long to wide format. The user would still need to state their parameter values (e.g. `clinical_emissions_data(wet_clinical_waste = "wet_waste")` etc. I have two suggestions, either:
1. The user would have to know their values in the `waste_type` variable so that when it is wide, they can then say which corresponds to which measure.
2. We have a "define" type function where the user can state which variable / variable value corresponds to what (e.g. if they have a value in their `waste_type` value, of `hdpeplastic`, this should be the variable value for any variable called "hdpe". They can also state here if kg/tonnes/etc.
